#Note that this file is not referenced by some settings.

#This is the setting of the robot's operation method. (kNone / kStraightMoveVector / kStraightMovePosition / kSpotTurnLastPosture / kSpotTurnRotAxis / kTurn)
operation_type = "kStraightMovePosition" 

[Param]
    
    #The value that is referenced when setting the camera to turn on the spot until it reaches the specified posture.
    spot_turn_last_posture = " 0.707,    -0.000,    -0.707,    -0.000"
    
    #The value referred to when setting up in-situ turning around the specified axis (in the direction of right-hand threads).
    spot_turn_rot_axis = "     0.000,     0.000,     1.000"
    
    #The value that is referred to when the setting is to go straight to the specified coordinates.
    #straight_move_position = " 100000000.000,     0.000,     0.000"
    straight_move_position = " 1000.000,     0.000,     1000.000"
    #straight_move_position = " 100000.000,   0.00,  100000.000"
    
    #The value that is referenced when the setting is to go straight in the specified direction.
    straight_move_vector = "     1.000,     0.000,     0.000"
    
    #The value referred to when setting the rotation around the specified center.
    turn_center = "     0.000,     0.000"
    
    #The value that is referenced when the setting is to turn in the specified direction.
    turn_clockwise = true
    
    #The value referenced in the case of a setup that turns at a specified radius.
    turn_radius = 1000.0
    
