
[Body]
    
    #Height at which the body is lifted from the ground [mm]. The maximum height can be raised to this level.
    body_lifting_height_max = 190.0
    
    #Height at which the body is lifted from the ground [mm]. The minimum height can be lowered to this level.
    body_lifting_height_min = 60.0

[CoxaRange]
    
    #Maximum leg range of motion [deg].
    movable_coxa_angle_max_deg = 35.0
    
    #Minimum leg movement range [deg].
    movable_coxa_angle_min_deg = -35.0

[LegRange]
    
    #Maximum distance from the base of the leg to the tip of the leg [mm].
    max_leg_range = 200.0
    
    #Minimum distance from the base of the leg to the tip of the leg [mm].
    min_leg_range = 135.0

[Other]
    
    #Height of the swing leg from the center of gravity [mm].
    free_leg_height = -40.0
    
    #Static safety margin: 15mm is a reasonable value. (Based on previous studies, max is about 40 mm.)
    stable_margin = 15.0
    
