#If this file is garbled, the problem is most likely due to character encoding.
#This file is written in utf - 8, and can be read by installing VS Code and configuring it to automatically detect the character encoding.
#This file is written in the TOML format. Just google it and you'll find easy to understand information on the wiki, so try looking it up.
#This file is a file for describing program settings.
#This file can also be edited with a text editor such as Notepad.
#If you want to change the simulation conditions, try changing them from here.Lines starting with a sharp are comments. They do not affect the program.


#Setting the mode in which the program is to be run
[Mode]
    
    #Ask the user about the run mode at startup. ( true / false )
    ask_about_modes = true
    
    #Sets the default run mode at startup. ( "kSimulation" / "kViewer" / "kDisplayModel" / "kResultViewer" / "kRobotControl" )
    default_mode = "kSimulation"
    
    #Ask if you want to continue with each move. ( true / false )
    do_step_execution_each_gait = false
    
    #Ask if you want to continue with each simulation. ( true / false )
    do_step_execution_each_simulation = true
    
#Program output settings.
[Output]
    
    #How much output is allowed on the command line. ( "kSystem" / "kError" / "kWarning" / "kInfo" / "kDebug" )
    cmd_output_detail = "kInfo"
    
    #Output characters to the command line. ( true / false )
    do_cmd_output = true
    
    #Display GUI. ( true / false )
    do_gui_display = true
    
    #GUI Image Qualityï¼Ž( "kLow" / "kMedium" / "kHigh" )
    gui_display_quality = "kHigh"
    
    #Sets FPS. The range is from 15 to 60. The recommended value is 60.
    window_fps = 60
    
    #Sets the width of the GUI. The range is from 512 to 1920. The recommended value is 1600.
    window_size_x = 1600
    
    #Sets the height of the GUI. The range is from 288 to 1080. The recommended value is 900.
    window_size_y = 900
    
#The order is major.minor.patch.
[Verion]
    version_major = 0
    version_minor = 5
    version_patch = 0
    
